[tool.poetry]
name = "prefect-cloud-run-poc"
version = "0.1.0"
description = ""
authors = ["Arthur Gusmão <arthurgusmao@id.uff.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gcsfs = "^2024.3.1"
prefect = "^2.16.8"
prefect-gcp = "^0.5.7"
dbt-bigquery = "^1.7.7"
prefect-dbt = {extras = ["bigquery"], version = "^0.4.1"}
beautifulsoup4 = "^4.12.3"
tqdm = "^4.66.2"
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
