{{ config(
          materialized='table',
          partition_by={
            "field": "data_referencia",
            "data_type": "date",
            "granularity": "month",
          },
          cluster_by=["versao",],) }}
SELECT
  SAFE_CAST(Data_Referencia AS DATE) AS data_referencia,
  SAFE_CAST(regexp_replace(CNPJ_Fundo, r'[^0-9]', '') AS STRING) AS cnpj_fundo,
  SAFE_CAST(substr(regexp_replace(CNPJ_Fundo, r'[^0-9]', ''), 1, 8) AS STRING) AS cnpj_basico,
  SAFE_CAST(Versao AS INT64) AS versao,
  SAFE_CAST(Data_Entrega AS DATE) AS data_entrega,
  SAFE_CAST(Nome_Fundo AS STRING) AS nome_fundo,
  SAFE_CAST(Data_Funcionamento AS DATE) AS data_funcionamento,
  SAFE_CAST(Publico_Alvo AS STRING) AS publico_alvo,
  SAFE_CAST(Codigo_ISIN AS STRING) AS codigo_isin,
  SAFE_CAST(Quantidade_Cotas_Emitidas AS FLOAT64) AS quantidade_cotas_emitidas,
  SAFE_CAST(Fundo_Exclusivo AS STRING) AS fundo_exclusivo,
  SAFE_CAST(Cotistas_Vinculo_Familiar AS STRING) AS cotistas_vinculo_familiar,
  SAFE_CAST(Mandato AS STRING) AS mandato,
  SAFE_CAST(Segmento_Atuacao AS STRING) AS segmento_atuacao,
  SAFE_CAST(Tipo_Gestao AS STRING) AS tipo_gestao,
  SAFE_CAST(Prazo_Duracao AS STRING) AS prazo_duracao,
  SAFE_CAST(Data_Prazo_Duracao AS DATE) AS data_prazo_duracao,
  SAFE_CAST(Encerramento_Exercicio_Social AS STRING) AS encerramento_exercicio_social,
  SAFE_CAST(Mercado_Negociacao_Bolsa AS STRING) AS mercado_negociacao_bolsa,
  SAFE_CAST(Mercado_Negociacao_MBO AS STRING) AS mercado_negociacao_mbo,
  SAFE_CAST(Mercado_Negociacao_MB AS STRING) AS mercado_negociacao_mb,
  SAFE_CAST(Entidade_Administradora_BVMF AS STRING) AS entidade_administradora_bvmf,
  SAFE_CAST(Entidade_Administradora_CETIP AS STRING) AS entidade_administradora_cetip,
  SAFE_CAST(Nome_Administrador AS STRING) AS nome_administrador,
  SAFE_CAST(CNPJ_Administrador AS STRING) AS cnpj_administrador,
  SAFE_CAST(Logradouro AS STRING) AS logradouro,
  SAFE_CAST(Numero AS STRING) AS numero,
  SAFE_CAST(Complemento AS STRING) AS complemento,
  SAFE_CAST(Bairro AS STRING) AS bairro,
  SAFE_CAST(Cidade AS STRING) AS cidade,
  SAFE_CAST(Estado AS STRING) AS estado,
  SAFE_CAST(CEP AS STRING) AS cep,
  SAFE_CAST(Telefone1 AS STRING) AS telefone1,
  SAFE_CAST(Telefone2 AS STRING) AS telefone2,
  SAFE_CAST(Telefone3 AS STRING) AS telefone3,
  SAFE_CAST(Site AS STRING) AS site,
  SAFE_CAST(Email AS STRING) AS email
FROM `arthur-data-engineering-course.brazilian_reits_staging.geral_staging`