queries:
  outputs:
    dev:
      dataset: brazilian_reits
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./dbt-service-account.json
      location: US
      method: service-account
      priority: interactive
      project: arthur-data-engineering-course
      threads: 4
      type: bigquery
  target: dev
