name: Lint Python
on: [workflow_dispatch, pull_request]

jobs:
  lint:
    name: Lint python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint source code
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'