name: Lint Python
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ricardochaves/python-lint@v1.4.0
